### ISSUE TITLE
Add possability to disable search options globally to reduce load to moodle

### ISSUE THREAD

**Issue by NiTRoeSE** [nextcloud/integration_moodle#17]
Hi, because of a high load on moodle instance generated by the course-search / search options it would be good if a administrator could disable this feature globally for all users.

Is there any way to do this ?
Thanks in advanced  :)

**Comment by eneiluj** [comment]
Right, this is something that could be done for most of the integration apps. Thanks for the suggestion.

It's done for this app and is included in v0.0.7 which I just released. There is now an option in connected accounts admin settings section.

Could you confirm it works?

**Comment by NiTRoeSE** [comment]
> Right, this is something that could be done for most of the integration apps. Thanks for the suggestion.
> 
> It's done for this app and is included in v0.0.7 which I just released. There is now an option in connected accounts admin settings section.
> 
> Could you confirm it works?

Hi, thank you very much for your really fast response & version 0.0.7.
I have tested it in our environment and it works like a charm, search option in user preferences is not shown /disabled  if admin has disabled it in "connected accounts" admin settings.

Thank you very much, it helped me a lot!
kind regards

**Comment by eneiluj** [comment]
Well thanks again for the suggestion. Glad you like the app and that it does not produce a huge load on your Moodle anymore.
