### ISSUE TITLE
Unable to connect to instance

### ISSUE THREAD

**Issue by MadFatVlad** [nextcloud/integration_moodle#9]
For some reason my school doesn't use HTTPS certificate on their server. Is it possible to access such instance?

**Comment by eneiluj** [comment]
v0.0.4 is out with a switch to disable SSL check. Could you check if it works fine?

**Comment by MadFatVlad** [comment]
For some reason, the URL is automatically prefixed with 'https://' and the app always tries to connect to port 443 (unsuccessfully).

**Comment by eneiluj** [comment]
Oh I thought you meant your Moodle instance was accessible with HTTPS but with an invalid certificate. v0.0.5 now allows HTTP instance addresses.

For the record, almost all other integration apps use OAuth to authenticate so I force HTTPS. As authentication is more basic for Moodle, we can allow HTTP. Keep in mind that your password is safe between your browser and your Nextcloud server BUT is visible by any entity between your Nextcloud server and your Moodle instance.

Thanks for the feedback!
